#!/usr/bin/env node
"use strict";

const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");

const repoRoot = path.resolve(__dirname, "..");
const chatRoot = path.join(repoRoot, "src", "gateway", "chat");
const staticRoot = path.join(chatRoot, "static");
const adminVendorRoot = path.join(
  repoRoot,
  "src",
  "gateway",
  "admin",
  "static",
  "vendor",
);
const babelPath = path.join(adminVendorRoot, "babel.min.js");

const pages = [
  {
    name: "chat",
    sourcePath: path.join(chatRoot, "chat.jsx"),
    htmlPath: path.join(staticRoot, "index.html"),
    outputPath: path.join(staticRoot, "chat.js"),
  },
  {
    name: "playground",
    sourcePath: path.join(chatRoot, "playground.jsx"),
    htmlPath: path.join(staticRoot, "playground.html"),
    outputPath: path.join(staticRoot, "playground.js"),
  },
  {
    name: "routing",
    sourcePath: path.join(chatRoot, "routing.jsx"),
    htmlPath: path.join(staticRoot, "routing.html"),
    outputPath: path.join(staticRoot, "routing.js"),
  },
];

const vendors = [
  {
    name: "react.production.min.js",
    sourcePath: path.join(adminVendorRoot, "react.production.min.js"),
    outputPath: path.join(
      staticRoot,
      "vendor",
      "react.production.min.js",
    ),
  },
  {
    name: "react-dom.production.min.js",
    sourcePath: path.join(
      adminVendorRoot,
      "react-dom.production.min.js",
    ),
    outputPath: path.join(
      staticRoot,
      "vendor",
      "react-dom.production.min.js",
    ),
  },
];

const csp =
  "default-src 'self'; base-uri 'none'; object-src 'none'; " +
  "form-action 'self'; connect-src 'self'; img-src 'self' data:; " +
  "font-src 'self' data:; style-src 'unsafe-inline'; " +
  "script-src 'self'; worker-src 'none'";

const legacyHeadPattern =
  /  <link rel="preconnect" href="https:\/\/fonts\.googleapis\.com">\n  <link href="https:\/\/fonts\.googleapis\.com\/css2\?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">\n  <script crossorigin src="https:\/\/unpkg\.com\/react@18\/umd\/react\.production\.min\.js"><\/script>\n  <script crossorigin src="https:\/\/unpkg\.com\/react-dom@18\/umd\/react-dom\.production\.min\.js"><\/script>\n  <script crossorigin src="https:\/\/unpkg\.com\/@babel\/standalone@7\.24\.7\/babel\.min\.js"><\/script>\n/;
const localHeadPattern =
  /  <meta http-equiv="Content-Security-Policy" content="[^"]+">\n  <!-- Chat runtime assets are vendored locally for offline and CSP-safe operation\. -->\n  <script src="\/chat\/static\/vendor\/react\.production\.min\.js\?v=(?:__DIGEST__|[a-f0-9]{64})"><\/script>\n  <script src="\/chat\/static\/vendor\/react-dom\.production\.min\.js\?v=(?:__DIGEST__|[a-f0-9]{64})"><\/script>\n/g;
const legacyInlinePattern =
  /  <script type="text\/babel">\n([\s\S]*?)\n  <\/script>/;

function fail(message) {
  console.error(`chat assets build: ${message}`);
  process.exitCode = 1;
}

function digest(content) {
  return crypto.createHash("sha256").update(content).digest("hex");
}

function relative(filePath) {
  return path.relative(repoRoot, filePath);
}

function compileSource(page) {
  const Babel = require(babelPath);
  const source = fs.readFileSync(page.sourcePath, "utf8");
  const transformed = Babel.transform(source, {
    ast: false,
    comments: true,
    compact: false,
    filename: path.basename(page.sourcePath),
    minified: false,
    presets: ["react"],
    sourceMaps: false,
  }).code;
  return (
    `// Generated by scripts/build_chat_assets.cjs from ` +
    `${relative(page.sourcePath)}. DO NOT EDIT.\n` +
    `${transformed.trimEnd()}\n`
  );
}

function localHead(vendorContents) {
  const reactDigest = digest(vendorContents.get("react.production.min.js"));
  const reactDOMDigest = digest(
    vendorContents.get("react-dom.production.min.js"),
  );
  return (
    `  <meta http-equiv="Content-Security-Policy" content="${csp}">\n` +
    "  <!-- Chat runtime assets are vendored locally for offline and " +
    "CSP-safe operation. -->\n" +
    "  <script src=\"/chat/static/vendor/react.production.min.js" +
    `?v=${reactDigest}\"></script>\n` +
    "  <script src=\"/chat/static/vendor/react-dom.production.min.js" +
    `?v=${reactDOMDigest}\"></script>\n`
  );
}

function validateHtml(html, page) {
  const scriptTags = [...html.matchAll(/<script\b([^>]*)>/gi)];
  if (scriptTags.length !== 3) {
    throw new Error(
      `${relative(page.htmlPath)} must contain exactly three scripts`,
    );
  }
  for (const match of scriptTags) {
    if (!/\bsrc="\/chat\/static\//.test(match[1])) {
      throw new Error(
        `${relative(page.htmlPath)} contains an inline or non-chat script`,
      );
    }
  }
  if (
    html.includes('type="text/babel"') ||
    /(?:src|href)="https?:\/\//i.test(html) ||
    /\/babel(?:\.min)?\.js/i.test(html)
  ) {
    throw new Error(
      `${relative(page.htmlPath)} still has a runtime compiler or ` +
        "external dependency",
    );
  }
  if (
    !html.includes('http-equiv="Content-Security-Policy"') ||
    !html.includes("script-src 'self'") ||
    html.includes("script-src 'self' 'unsafe-inline'")
  ) {
    throw new Error(
      `${relative(page.htmlPath)} must enforce same-origin scripts`,
    );
  }
}

function expectedHtml(page, compiled, vendorContents) {
  let html = fs.readFileSync(page.htmlPath, "utf8");
  const hardenedHead = localHead(vendorContents);
  if (legacyHeadPattern.test(html)) {
    html = html.replace(legacyHeadPattern, hardenedHead);
  } else {
    const headMatches = [...html.matchAll(localHeadPattern)];
    if (headMatches.length !== 1) {
      throw new Error(
        `${relative(page.htmlPath)} must contain one chat asset head block`,
      );
    }
    html = html.replace(localHeadPattern, hardenedHead);
  }

  const outputReference =
    `  <script src="/chat/static/${page.name}.js?v=${digest(compiled)}">` +
    "</script>";
  if (legacyInlinePattern.test(html)) {
    html = html.replace(legacyInlinePattern, outputReference);
  } else {
    const outputPattern = new RegExp(
      `  <script src="/chat/static/${page.name}\\.js\\?v=` +
        `(?:__DIGEST__|[a-f0-9]{64})"><\\/script>`,
      "g",
    );
    const outputMatches = [...html.matchAll(outputPattern)];
    if (outputMatches.length !== 1) {
      throw new Error(
        `${relative(page.htmlPath)} must contain one digest-bearing ` +
          `${page.name}.js reference`,
      );
    }
    html = html.replace(outputPattern, outputReference);
  }

  validateHtml(html, page);
  return html;
}

function writeIfChanged(filePath, content) {
  if (
    fs.existsSync(filePath) &&
    fs.readFileSync(filePath).equals(Buffer.from(content))
  ) {
    return;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
}

function main() {
  const args = new Set(process.argv.slice(2));
  const allowed = new Set(["--check"]);
  for (const argument of args) {
    if (!allowed.has(argument)) {
      throw new Error(`unknown argument ${argument}`);
    }
  }
  if (!fs.existsSync(babelPath)) {
    throw new Error(`${relative(babelPath)} is missing`);
  }

  const vendorContents = new Map();
  for (const vendor of vendors) {
    if (!fs.existsSync(vendor.sourcePath)) {
      throw new Error(`${relative(vendor.sourcePath)} is missing`);
    }
    vendorContents.set(vendor.name, fs.readFileSync(vendor.sourcePath));
  }

  const outputs = pages.map((page) => {
    if (!fs.existsSync(page.sourcePath)) {
      throw new Error(`${relative(page.sourcePath)} is missing`);
    }
    const compiled = compileSource(page);
    return {
      page,
      compiled,
      html: expectedHtml(page, compiled, vendorContents),
    };
  });

  if (args.has("--check")) {
    for (const vendor of vendors) {
      if (!fs.existsSync(vendor.outputPath)) {
        fail(`${relative(vendor.outputPath)} is missing`);
      } else if (
        !fs
          .readFileSync(vendor.outputPath)
          .equals(vendorContents.get(vendor.name))
      ) {
        fail(`${relative(vendor.outputPath)} is stale`);
      }
    }
    for (const { page, compiled, html } of outputs) {
      if (!fs.existsSync(page.outputPath)) {
        fail(`${relative(page.outputPath)} is missing`);
      } else if (
        fs.readFileSync(page.outputPath, "utf8") !== compiled
      ) {
        fail(
          `${relative(page.outputPath)} is stale; run ` +
            "node scripts/build_chat_assets.cjs",
        );
      }
      if (fs.readFileSync(page.htmlPath, "utf8") !== html) {
        fail(
          `${relative(page.htmlPath)} has stale asset digests; run ` +
            "node scripts/build_chat_assets.cjs",
        );
      }
    }
    if (process.exitCode !== 1) {
      console.log("chat generated assets are current");
    }
    return;
  }

  for (const vendor of vendors) {
    writeIfChanged(
      vendor.outputPath,
      vendorContents.get(vendor.name),
    );
  }
  for (const { page, compiled, html } of outputs) {
    writeIfChanged(page.outputPath, compiled);
    writeIfChanged(page.htmlPath, html);
  }
  console.log("wrote chat bundles, vendored runtimes, and synchronized HTML");
}

try {
  main();
} catch (error) {
  fail(error instanceof Error ? error.message : String(error));
}
