#!/usr/bin/env node
"use strict";

const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");

const repoRoot = path.resolve(__dirname, "..");
const sourcePath = path.join(
  repoRoot,
  "src",
  "gateway",
  "admin",
  "dashboard.jsx",
);
const indexPath = path.join(
  repoRoot,
  "src",
  "gateway",
  "admin",
  "static",
  "index.html",
);
const outputPath = path.join(
  repoRoot,
  "src",
  "gateway",
  "admin",
  "static",
  "dashboard.js",
);
const babelPath = path.join(
  repoRoot,
  "src",
  "gateway",
  "admin",
  "static",
  "vendor",
  "babel.min.js",
);

const externalScriptPattern =
  /  <script src="\/admin\/static\/dashboard\.js\?v=(?:__DIGEST__|[a-f0-9]{64})"><\/script>/g;

function fail(message) {
  console.error(`admin dashboard build: ${message}`);
  process.exitCode = 1;
}

function compileSource() {
  const Babel = require(babelPath);
  const source = fs.readFileSync(sourcePath, "utf8");
  const transformed = Babel.transform(source, {
    ast: false,
    comments: true,
    compact: false,
    filename: "dashboard.jsx",
    minified: false,
    presets: ["react"],
    sourceMaps: false,
  }).code;
  return (
    "// Generated by scripts/build_admin_dashboard.cjs from " +
    "src/gateway/admin/dashboard.jsx. DO NOT EDIT.\n" +
    `${transformed.trimEnd()}\n`
  );
}

function expectedIndex(compiled) {
  const digest = crypto.createHash("sha256").update(compiled).digest("hex");
  const reference =
    `  <script src="/admin/static/dashboard.js?v=${digest}"></script>`;
  const index = fs.readFileSync(indexPath, "utf8");
  const matches = [...index.matchAll(externalScriptPattern)];
  if (matches.length !== 1) {
    throw new Error(
      "index.html must contain exactly one digest-bearing dashboard.js reference",
    );
  }
  if (
    index.includes('type="text/babel"') ||
    index.includes("/admin/static/vendor/babel.min.js")
  ) {
    throw new Error("index.html still loads the browser Babel runtime");
  }
  return index.replace(externalScriptPattern, reference);
}

function writeIfChanged(filePath, content) {
  if (fs.existsSync(filePath) && fs.readFileSync(filePath, "utf8") === content) {
    return;
  }
  fs.writeFileSync(filePath, content, "utf8");
}

function main() {
  const args = new Set(process.argv.slice(2));
  const allowed = new Set(["--check"]);
  for (const argument of args) {
    if (!allowed.has(argument)) {
      throw new Error(`unknown argument ${argument}`);
    }
  }
  if (!fs.existsSync(sourcePath)) {
    throw new Error(`${path.relative(repoRoot, sourcePath)} is missing`);
  }

  const compiled = compileSource();
  const index = expectedIndex(compiled);
  if (args.has("--check")) {
    if (!fs.existsSync(outputPath)) {
      fail(`${path.relative(repoRoot, outputPath)} is missing`);
    } else if (fs.readFileSync(outputPath, "utf8") !== compiled) {
      fail("dashboard.js is stale; run node scripts/build_admin_dashboard.cjs");
    }
    if (fs.readFileSync(indexPath, "utf8") !== index) {
      fail(
        "index.html has a stale dashboard.js digest; " +
          "run node scripts/build_admin_dashboard.cjs",
      );
    }
    if (process.exitCode !== 1) {
      console.log("admin dashboard generated assets are current");
    }
    return;
  }

  writeIfChanged(outputPath, compiled);
  writeIfChanged(indexPath, index);
  console.log(
    `wrote ${path.relative(repoRoot, outputPath)} and synchronized index.html`,
  );
}

try {
  main();
} catch (error) {
  fail(error instanceof Error ? error.message : String(error));
}
